name: wortspion
description: "Ein soziales Deduktionsspiel, bei dem Spieler ein Wort kennen, während Spione versuchen, unentdeckt zu bleiben."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Dependency Injection
  get_it: ^7.6.0
  
  # Lokale Datenbank
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path_provider: ^2.1.0
  path: ^1.8.3
  
  # UI Utilities
  google_fonts: ^5.1.0
  flutter_animate: ^4.2.0
  
  # Routing
  auto_route: ^7.8.0
  
  # Utilities
  uuid: ^3.0.7
  intl: ^0.18.1
  logger: ^2.0.1
  shared_preferences: ^2.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  
  # Code Generation
  build_runner: ^2.4.6
  auto_route_generator: ^7.3.1
  
  # Testing
  bloc_test: ^9.1.4
  mockito: ^5.4.2

flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/fonts/
    - assets/images/spies/
    - assets/images/saboteurs/
    - assets/images/teammembers/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
